spring:
  datasource:
    driver-class-name:
    username:
    password:
    url:

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          timeout:
          starttls:
            enable:

server:
  servlet:
    session:
      timeout: 15m

---
spring:
  profiles:
    active: dev