spring:
  datasource:
    driver-class-name:
    username:
    password:
    url:

  mail:
    host:
    port:
    username:
    password:
    properties:
      mail:
        smtp:
          auth:
          timeout:
          starttls:
            enable:

---
spring:
  profiles:
    active: dev